objects = regenerate.o handler.o

all:ofpsvr
ofpsvr:main.c $(objects)
	cc main.c $(objects) -o $@ -I../mruby/include -L/usr/local/lib ../mruby/build/host/lib/libmruby.a -lm -lmysqlclient -lcrypto -lmicrohttpd -lpthread -O3
$(objects): %.o: %.c
	cc $< -o $@ -c -I../mruby/include -L/usr/local/lib ../mruby/build/host/lib/libmruby.a -lm -lmysqlclient -lcrypto -lmicrohttpd -lpthread -O3
install:ofpsvr
	cp ./ofpsvr /usr/local/bin
clean:
	rm *.o ./ofpsvr
